# Generated by Django 2.0.2 on 2018-02-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='picModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
