# Generated by Django 2.0.2 on 2018-02-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0002_auto_20180208_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='picmodel',
            name='pic_class',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picmodel',
            name='sourceValid',
            field=models.BooleanField(default=1),
        ),
    ]
