# Generated by Django 2.0.2 on 2018-02-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0003_auto_20180222_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='picmodel',
            name='thumbnail',
            field=models.CharField(default='', max_length=200),
        ),
    ]
